pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                echo "Cloning repo..."
                git url: 'https://github.com/SparshithaMaithri/MyDemoApp.git', branch: 'master'
            }
        }

        stage('Build') {
            steps {
                echo "Cleaning and building the project..."
                bat "mvn clean compile"
            }
        }

        stage('Test') {
            steps {
                echo "Running tests..."
                bat "mvn test"
            }
        }

        stage('Deploy and Package') {
            steps {
                echo "Packaging application..."
                bat "mvn package"
            }
        }

        stage('Archive Artifacts') {
            steps {
                echo "Archiving artifacts..."
                archiveArtifacts artifacts: 'target/*.jar'
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed. Please check the logs.'
        }
    }
}
